export const DISMISS_MESSAGE = 'DISMISS_MESSAGE';

export const CREATE_FLAT = 'CREATE_FLAT';
export const CREATE_SUCCESS_FLAT = 'CREATE_SUCCESS_FLAT';
export const CREATE_ERROR_FLAT = 'CREATE_ERROR_FLAT';

export const CREATE_OUTING = 'CREATE_OUTING';
export const CREATE_SUCCESS_OUTING = 'CREATE_SUCCESS_OUTING';
export const CREATE_ERROR_OUTING = 'CREATE_ERROR_OUTING';
export const SHOW_USER_OUTINGS = 'SHOW_USER_OUTINGS';

export const TOGGLE_LOGIN_MODE = 'TOGGLE_LOGIN_MODE';
export const MANUAL_LOGIN_USER = 'MANUAL_LOGIN_USER';
export const LOGIN_SUCCESS_USER = 'LOGIN_SUCCESS_USER';
export const LOGIN_ERROR_USER = 'LOGIN_ERROR_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_SUCCESS_USER = 'SIGNUP_SUCCESS_USER';
export const SIGNUP_ERROR_USER = 'SIGNUP_ERROR_USER';
export const EDIT_USER = 'EDIT_USER';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_ERROR = 'EDIT_USER_ERROR';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_SUCCESS_USER = 'LOGOUT_SUCCESS_USER';
export const LOGOUT_ERROR_USER = 'LOGOUT_ERROR_USER';
export const USER_FETCH = 'USER_FETCH';
export const USER_FETCH_SUCCESS = 'USER_FETCH_SUCCESS';
export const USER_FETCH_ERROR = 'USER_FETCH_ERROR';
